### ISSUE TITLE
wrong args for environment subassignment and more

### ISSUE THREAD

**Issue by sum732** [gacatag/IntEREst#10] opened 2019-07-27 18:23 UTC
Hi,

Below is the command that I used to calculate intron:exon ratio for a sample
```
interest(bamFileYieldSize=1000000, 
          bamFile="/data/fastq/Sample_226a/analysis/star/Sample_226a.Aligned.sortedByCoord.out.bam", 
          isPaired=TRUE,
          isPairedDuplicate=FALSE, 
          isSingleReadDuplicate= FALSE, reference=testRef,
         referenceIntronExon=testRef[,"int_ex"],
          junctionReadsOnly=FALSE, 
          outFile="/data/fastq/analysis/interestRes_Sample_226a.tsv", 
          logFile="/data/fastq/analysis/log.txt",
          returnObj= FALSE,
          method=c("IntRet", "ExEx"),
          appendLogFile=FALSE, 
          clusterNo=8,
          sampleName="Sample_226a",
          scaleLength= c(TRUE,FALSE), 
          scaleFragment= c(TRUE,TRUE))
```
I am seeing following error messages and not sure what to make of them

```
Error in env[[as.character(i)]] <- value : 
  wrong args for environment subassignment
```
and
```
> Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
```
If you give me some details to figure/fix the issues, will be of great help. 

Thanks,
S

**Comment by gacatag** [comment] 2019-07-30 16:16
Hi @sum732 !
Using the parameter settings that you listed above on a small test _.bam_ file, I was not able to replicate the error you mentioned. To see what may be the cause of the error, could you send me the result of the following scripts:

```
# Return the version of IntEREst
packageVersion("IntEREst")

# Show top rows of your reference
head(testRef)

# Show the first rows of the bamfile, e.g. on Linux system try
system(command="samtools view /data/fastq/Sample_226a/analysis/star/Sample_226a.Aligned.sortedByCoord.out.bam  | head", intern = TRUE)

# Show session info
sessionInfo()
```
 
Cheers!

Ali

**Comment by sum732** [comment] 2019-07-31 17:56
Thanks for writing back about the issue. 
One error 
```
Error in env[[as.character(i)]] <- value : 
  wrong args for environment subassignment
```
went away using
```
referenceGeneNames=FALSE
```
The other error, some memory issue with R as with small file it worked but analyzing 300 million reads something was not happy. 

about the referenceGeneNames, is there a way within "referencePrepare" function to actually create another column with gene names? 
Right now only header produced are 
```
chr 
begin 
end 
strand 
int_ex 
int_ex_num 
collapsed_transcripts_id 
collapsed_transcripts
```
The input is a GTF file. 

Thanks
S

**Comment by gacatag** [comment] 2019-08-01 09:36
Hi again!

If you have set the read counts to be scaled (`scaleFragment=TRUE`) the scaling of reads/fragments is gene (or better say 'transcript') wide. so it is better that instead of `referenceGeneNames=FALSE` you set `scaleFragment=testRef[,"collapsed_transcripts_id"]` .

Because by default it is set that `bamFileYieldSize=1000000`, 1million mapped reads are read from the bam file at a time. If you have limited memory you can of course decrease _bamFileYieldSize_ to a smaller value (_e.g._ 10000) based on your memory limit. 

> about the referenceGeneNames, is there a way within "referencePrepare" function to actually create another column with gene names?

What did you use to generate reference? I mean, what was your `sourceBuild` setting in the `referencePrepare` ?  There is a `annotateGeneIds` option that if set TRUE it should return gene IDs as well however that does not work with all sourceBuilds at the moment unfortunately. 

Do let me know if the above info helped you overcome the issues or if you had other questions.

Cheers,

Ali

**Comment by sum732** [comment] 2019-08-01 20:26
Thanks Ali.
About the ``` bamFileYieldSize``` I did played with and reduced it. Had to quite the session a few times. Some how, even on a cluster, I was having memory issues. But this is resolved.

I am using ```annotateGeneIds=TRUE``` but don't see the column in the file. 
The input file is standard v19 human gencode GTF file. 
``` 
testRef<- referencePrepare(sourceBuild="file", 
                           filePath="gencode.v19.annotation.gtf",
                            collapseExons=TRUE,
                            fileFormat="gtf", 
                             addCollapsedTranscripts=TRUE,
                             ignore.strand=FALSE,
                            annotateGeneIds=TRUE)
```
```
head(testRefGff)
  chr begin   end strand int_ex int_ex_num collapsed_transcripts_id collapsed_transcripts
```
Thank you for the suggestion to use ``` referenceGeneNames=FALSE```

Another thing I am trying to figure out and confirm is when intronic(or exonic) regions are shared within the transcripts of the same gene or another gene, what happen in this case, meaning how are reads assigned?  I think you are using "GenomicFeature" function to do this, but I am not able to figure this out. 
I am looking for the case best explained in featureCount (or from HTSeqCount image and I guess with "union" as choice) from Subread where exon (gene) expression is produced and reads are either counted once or not counted when exons are overlapping with different genes (based on some parameters). 

Best,
S

**Comment by gacatag** [comment] 2019-08-02 09:25
> Another thing I am trying to figure out and confirm is when intronic(or exonic) regions are shared within the transcripts of the same gene or another gene, what happen in this case, meaning how are reads assigned? I think you are using "GenomicFeature" function to do this, but I am not able to figure this out.
> I am looking for the case best explained in featureCount (or from HTSeqCount image and I guess with "union" as choice) from Subread where exon (gene) expression is produced and reads are either counted once or not counted when exons are overlapping with different genes (based on some parameters).

Hi again!
The way that we have described and suggested in [IntEREst vignette document](https://bioconductor.org/packages/release/bioc/vignettes/IntEREst/inst/doc/IntEREst.html#difanalysis) is that you would need to generate 2 separate references: 
-  One would be used to count the reads that map to the introns (i.e. map within the introns and to the intron-exon junction) and has all the exonic areas collapsed and merged to one another. 
- Another reference is needed that it is the _uncollapsed_ reference and it is used for counting reads that span the introns. This reference incldues intronic and exonic coordinates of the transcripts as they are defined in ENSEMBL or REFSEQ. 

For counting the intron mapping reads we sum over the intronic read counts of _exon-collapsed_ reference to get the intron mapping read counts. This means that we also exclude the reads that map to any exon across the isoforms.

Sorry about the confusion if it is not completely clear from the vignette; I am actually preparing a wrapper function that I'll probably call `interesting()` :smiley:  that performs the differential alternative splicing routines described in the vignette under ["Our recommended pipeline for differential intron retention analysis"](https://bioconductor.org/packages/release/bioc/vignettes/IntEREst/inst/doc/IntEREst.html#difanalysis) . I'll clarify and include these details in the manual of that function and in the vignette.

Cheers,

Ali

**Comment by sum732** [comment] 2019-08-02 11:19
Thanks Ali,
So to make it clear, create two objects, 1) ``` method="IntRet" and junctionReadsOnly= FALSE``
and 2) ``` method="IntSpan" ```  and then to know the ratio use ``` deseqIntEREst() ``` on the objects from 1 and 2. 
About the junctions, how much overhang/bases are considered for intron-exon junctions? 
Also no special considerations to CDS, 5'UTRs, 3'UTRs for exonic reads correct? 

Any idea as to why with ``` annotateGeneIds=TRUE)``` still not the corresponding column? 

Best,
S

**Comment by gacatag** [comment] 2019-08-02 11:29
Hi!

> About the junctions, how much overhang/bases are considered for intron-exon junctions?

Basically, any overlap (i.e. > 0 bases) is considered.

> Also no special considerations to CDS, 5'UTRs, 3'UTRs for exonic reads correct?

Sorry this is a bit unclear to me. What kind of considerations are you referring to ?

**Comment by gacatag** [comment] 2019-08-02 11:45
> So to make it clear, create two objects, 1) ``` method="IntRet" and junctionReadsOnly= FALSE``
> and 2) ``` method="IntSpan" ```  and then to know the ratio use ``` deseqIntEREst() ``` on the objects from 1 and 2. 

Yes; That is the idea. To run `method="IntSpan"` on uncollapsed reference and to run the `method="IntRet"` with `junctionReadsOnly=FALSE` on the exon-collapsed reference.

Cheers,

Ali

**Comment by sum732** [comment] 2019-08-02 13:43
> Hi!
> 
> > About the junctions, how much overhang/bases are considered for intron-exon junctions?
> 
> Basically, any overlap (i.e. > 0 bases) is considered.
> 
> > Also no special considerations to CDS, 5'UTRs, 3'UTRs for exonic reads correct?
> 
> Sorry this is a bit unclear to me. What kind of considerations are you referring to ?

That is my bad. I am referring to how RSeQC does this, direct link
http://rseqc.sourceforge.net/#read-distribution-py
Here they are stating that if reads overlap then they a set of criteria how they will assign the reads. 

So I am just checking if there is preference here.

**Comment by gacatag** [comment] 2019-08-02 14:11
I assume you are referring to summarization of intron-spanning reads (i.e. the `interest()` run with `method="IntSpan"` ) ? No; no special consideration is taken into account. It would return the number of intron-spanning reads that map to any exon.

**Closed as completed** 2019-08-29 08:29 UTC
